# Guided practice
for i in range(5):
    print(i)        # executes and displays the numbers 0 to 4, stopping before 5
for letter in 'data':
    print(letter)   # executes and displays each letter in the string 'data'
for n in range(2, 10, 3):
    print(n)        # executes and displays the numbers 2, 5, 8, stopping before 10

# Practice Task and Stretch Challenge
# Task one
number = int(input("Enter a number to see its multiplication table: "))
for multiply in range(1, 13):
    result = number * multiply
    print(f"{number} x {multiply} = {result}")
# Task two
word = input("Enter a word to see its letters printed in reverse: ")
reversed_word = ''.join(word[i] for i in range(len(word) - 1, -1, -1))
print(reversed_word)

# stretch challenge
numbers = 1, 2, 3, 4, 5
range_is = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)

for number in numbers:
    for multiply in range_is:
        result = number * multiply
        print(f"{number} x {multiply} = {result}")     # the nested for loop is used to create a multiplication table for the numbers 1 to 5, with each number being multiplied by the numbers in the range from 1 to 12. The result of each multiplication is printed in a formatted string.

sentence = "I am a boy who plays football."
for vowels in sentence:
    if vowels in "aeiouAEIOU":
        count = sentence.count(vowels)
print(f"Total number of vowels in the sentence: {sum(1 for char in sentence if char in 'aeiouAEIOU')}")  # this line counts the total number of vowels in the sentence by using a generator expression that iterates through each character in the sentence and checks if it is a vowel. The sum function then adds up all the 1s generated by the expression, giving the total count of vowels.