# Guided practice
for i in range(5):
    print(i)        # executes and displays the numbers 0 to 4, stopping before 5
for letter in 'data':
    print(letter)   # executes and displays each letter in the string 'data'
for n in range(2, 10, 3):
    print(n)        # executes and displays the numbers 2, 5, 8, stopping before 10

# Practice Task and Stretch Challenge
# Task one
number = int(input("Enter a number to see its multiplication table: "))
for multiply in range(1, 13):
    result = number * multiply
    print(f"{number} x {multiply} = {result}")
# Task two
word = input("Enter a word to see its letters printed vertically in reverse: ")
for letter in reversed(word):
    print(letter)       # the reverse function is used to reverse the order of the letters in the word, and then each letter is printed on a new line

numbers = 1, 2, 3, 4, 5
range_is = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)

for number in numbers:
    for range in range_is:
        result = number * range
        print(f"{number} x {range} = {result}")     # the nested for loop is used to create a multiplication table for the numbers 1 to 5, with each number being multiplied by the numbers in the range from 1 to 12. The result of each multiplication is printed in a formatted string.

sentence = "I am a boy who plays football."
for vowels in sentence:
    if vowels in "aeiouAEIOU":
        count = sentence.count(vowels)
        print(f"{vowels}: {count}")       # the for loop iterates through each character in the sentence, and the if statement checks if the character is a vowel (either lowercase or uppercase). If it is a vowel, it is printed to the console along with its count.
        print(f"Total number of vowels in the sentence: {sum(1 for char in sentence if char in 'aeiouAEIOU')}")  # this line counts the total number of vowels in the sentence by using a generator expression that iterates through each character in the sentence and checks if it is a vowel. The sum function then adds up all the 1s generated by the expression, giving the total count of vowels.